2019-11-04 09:36:42.780 [error] <0.349.0> gen_server <0.349.0> terminated with reason: {socket_error,timeout}
2019-11-04 09:36:42.801 [error] <0.350.0> gen_server <0.350.0> terminated with reason: {socket_error,timeout}
2019-11-04 09:36:42.801 [error] <0.372.0> gen_server <0.372.0> terminated with reason: {socket_error,timeout}
2019-11-04 09:36:42.801 [error] <0.337.0> gen_server <0.337.0> terminated with reason: {socket_error,timeout}
2019-11-04 09:36:42.833 [error] <0.340.0> gen_server <0.340.0> terminated with reason: {socket_error,timeout}
2019-11-04 09:36:42.833 [error] <0.368.0> gen_server <0.368.0> terminated with reason: {socket_error,timeout}
2019-11-04 09:36:43.012 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 09:36:43.013 [error] <0.337.0> CRASH REPORT Process <0.337.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 09:36:43.013 [error] <0.340.0> CRASH REPORT Process <0.340.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 09:36:43.015 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.340.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 09:36:43.015 [error] <0.338.0> Supervisor {<0.338.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.339.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.340.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 09:36:43.016 [error] <0.366.0> Supervisor {<0.366.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.367.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.368.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 09:36:43.017 [error] <0.366.0> Supervisor {<0.366.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.367.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.368.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 09:36:43.017 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.334.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.337.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 09:36:43.018 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.334.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.337.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 11:06:32.688 [error] <0.572.0> gen_server <0.572.0> terminated with reason: {socket_error,timeout}
2019-11-04 13:00:24.010 [error] <0.645.0> gen_server <0.645.0> terminated with reason: {socket_error,timeout}
2019-11-04 13:00:24.161 [error] <0.645.0> CRASH REPORT Process <0.645.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 13:00:24.161 [error] <0.637.0> gen_server <0.637.0> terminated with reason: {socket_error,timeout}
2019-11-04 13:00:24.413 [error] <0.636.0> Supervisor {<0.636.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.637.0>, <0.643.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52176 -> 127.0.0.1:5672">>) at <0.645.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 13:00:24.414 [error] <0.636.0> Supervisor {<0.636.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.637.0>, <0.643.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52176 -> 127.0.0.1:5672">>) at <0.645.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 13:00:24.414 [error] <0.637.0> CRASH REPORT Process <0.637.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 13:00:24.414 [error] <0.641.0> gen_server <0.641.0> terminated with reason: {socket_error,timeout}
2019-11-04 13:00:24.414 [error] <0.641.0> CRASH REPORT Process <0.641.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 13:00:24.414 [error] <0.635.0> Supervisor {<0.635.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.636.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.637.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 13:00:24.414 [error] <0.635.0> Supervisor {<0.635.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.636.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.637.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 13:00:24.414 [error] <0.634.0> gen_server <0.634.0> terminated with reason: {socket_error,timeout}
2019-11-04 13:00:24.414 [error] <0.634.0> CRASH REPORT Process <0.634.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-11-04 13:00:24.414 [error] <0.633.0> Supervisor {<0.633.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.634.0>, <0.639.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52175 -> 127.0.0.1:5672">>) at <0.641.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 13:00:24.414 [error] <0.633.0> Supervisor {<0.633.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.634.0>, <0.639.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52175 -> 127.0.0.1:5672">>) at <0.641.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 13:00:24.415 [error] <0.632.0> Supervisor {<0.632.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.633.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.634.0> exit with reason {socket_error,timeout} in context child_terminated
2019-11-04 13:00:24.415 [error] <0.632.0> Supervisor {<0.632.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.633.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun amqp_a..>,...],...}) at <0.634.0> exit with reason reached_max_restart_intensity in context shutdown
2019-11-04 13:38:55.251 [error] <0.672.0> gen_server <0.672.0> terminated with reason: {socket_error,timeout}
2019-11-04 13:38:55.680 [error] <0.676.0> gen_server <0.676.0> terminated with reason: {socket_error,timeout}
